name: Publish
on:
  workflow_dispatch:
    inputs:
      version_type:
        description: "Bump version"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure latest content
        run: |
          git checkout main
          git pull origin main

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: "https://registry.npmjs.org/"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run linter
        working-directory: packages/cachebay
        run: pnpm lint
        continue-on-error: true

      - name: Build package
        working-directory: packages/cachebay
        run: pnpm build

      - name: Run tests
        working-directory: packages/cachebay
        run: pnpm test

      - name: Install Playwright
        run: pnpm --filter benchmarks exec playwright install chromium

      - name: Run DOM benchmarks
        run: pnpm --filter benchmarks bench:ci:baseline:suite

      - name: Run API benchmarks
        run: pnpm --filter benchmarks bench:ci:baseline:api

      - name: Bump version
        run: pnpm bump ${{ github.event.inputs.version_type }}

      - name: Copy docs
        run: |
          cp -r ./docs ./packages/cachebay/docs
          cp ./LICENSE.md ./packages/cachebay/LICENSE.md
          cp ./README.md ./packages/cachebay/README.md

      - name: Commit all bump changes
        run: |
          VERSION=$(node -p "require('./packages/cachebay/package.json').version")
          git config user.name "LockVoid /dev/null"
          git config user.email "dev@lockvoid.com"
          git add .
          git commit -m "$VERSION"

      - name: Create tag
        run: |
          VERSION=$(node -p "require('./packages/cachebay/package.json').version")
          git tag "v$VERSION"

      - name: Push commit and tag
        run: |
          git push
          git push --tags

      - name: Publish to npm
        working-directory: packages/cachebay
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
